# start inside pennovation
- position: [16, -1.7, 4]
- position: [9.4, -36.2, 3]
# exit pennovation, enter park
- position: [32.1, -49.6, 2]
- position: [56.7, -20.6, 2]
- position: [85.5, 11.5, 3]
- position: [99.7, 51.8, 4]
- position: [119.5, 131.2, 4]
- position: [99.7, 51.8, 4]
- position: [85.5, 11.5, 3]
- position: [56.7, -20.6, 2]
- position: [32.1, -49.6, 2]
# exit park, return pennovation
- position: [-24.7, -55.9, 2.5]
- position: [-105.0, -52.0, 3.5] # center of grass
- position: [-185.0, -50.0, 3.5] # between trees
- position: [-145.5, -9.1, 3.0] # in parking lot
- position: [-105.0, -52.0, 3.5] # center of grass
- position: [-53.6, -38.8, 5] # top of hill
- position: [0, 0, 3] # back home

