name: docker-build-control

# Build estimation when "base" changes, or when any files in the estimation
# folder are modified
on:
  workflow_run:
    workflows: ["docker-build-base"]
    branches: [master]
    types:
      - completed
  push:
    paths:
    - 'control/**'
    branches: [master, control_in_repo]

jobs:
  main:
    runs-on: ubuntu-18.04

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kumarrobotics/autonomy:control
          file: ./estimation/Dockerfile
          # platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
